/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#191a1a',
        error: '#ec7c8a',
        'on-secondary-fixed': '#2b424d',
        'surface-container-low': '#131313',
        outline: '#767575',
        tertiary: '#f3faff',
        'surface-tint': '#bac3ff',
        'surface-container-highest': '#252626',
        'secondary-container': '#273f49',
        'surface-dim': '#0e0e0e',
        'primary-fixed': '#dee0ff',
        'on-secondary': '#09232d',
        'on-tertiary-fixed-variant': '#556369',
        'on-primary-fixed': '#27378a',
        'tertiary-dim': '#d1dfe6',
        'on-surface-variant': '#acabaa',
        'on-tertiary-fixed': '#39474c',
        'tertiary-container': '#dfedf5',
        'inverse-primary': '#4958ac',
        'on-primary': '#28388b',
        'surface-variant': '#252626',
        'inverse-on-surface': '#565555',
        'error-dim': '#b95463',
        'tertiary-fixed': '#dfedf5',
        'on-primary-fixed-variant': '#4555a8',
        primary: '#bac3ff',
        'primary-dim': '#a8b4ff',
        'on-error': '#490013',
        'inverse-surface': '#fcf9f8',
        'primary-fixed-dim': '#ccd2ff',
        background: '#0e0e0e',
        'tertiary-fixed-dim': '#d1dfe6',
        'on-tertiary-container': '#4b595f',
        'secondary-fixed': '#cde6f4',
        'on-secondary-fixed-variant': '#475f6a',
        'on-error-container': '#ff97a3',
        'on-tertiary': '#546167',
        'on-secondary-container': '#aac3d0',
        'surface-bright': '#2b2c2c',
        'surface-container-high': '#1f2020',
        'on-primary-container': '#c7cdff',
        surface: '#0e0e0e',
        'secondary-dim': '#89a1ae',
        'primary-container': '#2f3f92',
        secondary: '#89a1ae',
        'surface-container-lowest': '#000000',
        'outline-variant': '#484848',
        'on-surface': '#e7e5e5',
        'secondary-fixed-dim': '#bfd8e5',
        'on-background': '#e7e5e5',
        'error-container': '#7f2737',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        mock: '0.75rem',
      },
    },
  },
};
